# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: console

release:
  name_template: "Release version {{.Tag}}"
  github:
    owner: Computomics
    name: console-ctx

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    main: ./cmd/console/
    flags:
      - -trimpath
      - --tags=kqueue,operator
    ldflags:
      - -s -w -X github.com/minio/console/pkg.ReleaseTag={{.Tag}} -X github.com/minio/console/pkg.CommitID={{.FullCommit}} -X github.com/minio/console/pkg.Version={{.Version}} -X github.com/minio/console/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/console/pkg.ReleaseTime={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats: [ "binary" ]

snapshot:
  version_template: SNAPSHOT@{{.ShortCommit}}

changelog:
  sort: asc

nfpms:
  - vendor: "Computomics"
    homepage: https://github.com/Computomics/console-ctx
    maintainer: "Computomics"
    description: Console UI for MinIO Server (Computomics branded)
    license: GNU Affero General Public License v3.0
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
    contents:
      - src: systemd/console.service
        dst: /etc/systemd/system/minio-console.service

dockers:
  - image_templates:
      - "ghcr.io/computomics/console-ctx:{{ .Tag }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=TAG={{ .Tag }}"
  - image_templates:
      - "ghcr.io/computomics/console-ctx:{{ .Tag }}-arm64"
    use: buildx
    goarch: arm64
    goos: linux
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=TAG={{ .Tag }}"

docker_manifests:
  - name_template: ghcr.io/computomics/console-ctx:{{ .Tag }}
    image_templates:
      - ghcr.io/computomics/console-ctx:{{ .Tag }}-amd64
      - ghcr.io/computomics/console-ctx:{{ .Tag }}-arm64
  - name_template: ghcr.io/computomics/console-ctx:latest
    image_templates:
      - ghcr.io/computomics/console-ctx:{{ .Tag }}-amd64
      - ghcr.io/computomics/console-ctx:{{ .Tag }}-arm64
