# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: console

release:
  name_template: "Release version {{.Tag}}"
  github:
    owner: georgmangold
    name: console

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    main: ./cmd/console/
    flags:
      - -trimpath
      - --tags=kqueue,operator
    ldflags:
      - -s -w -X github.com/minio/console/pkg.ReleaseTag={{.Tag}} -X github.com/minio/console/pkg.CommitID={{.FullCommit}} -X github.com/minio/console/pkg.Version={{.Version}} -X github.com/minio/console/pkg.ShortCommitID={{.ShortCommit}} -X github.com/minio/console/pkg.ReleaseTime={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats: ["binary"]

snapshot:
  version_template: SNAPSHOT@{{.ShortCommit}}

changelog:
  sort: asc

nfpms:
  - vendor: "Georg Mangold"
    homepage: https://github.com/georgmangold/console
    maintainer: "Georg Mangold"
    description: Console UI for MinIO Server
    license: GNU Affero General Public License v3.0
    bindir: /usr/local/bin
    formats:
      - deb
      - rpm
    contents:
      # Basic file that applies to all packagers
      - src: systemd/console.service
        dst: /etc/systemd/system/minio-console.service

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - "ghcr.io/georgmangold/console"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ .Tag }}"
      - "latest"
    build_args:
      TAG: "{{ .Tag }}"
    labels:
      "org.opencontainers.image.authors": "Georg Mangold"
      "org.opencontainers.image.vendor": "Georg Mangold"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.description": "A graphical user interface for MinIO®"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Tag}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
      "org.opencontainers.image.documentation": "{{.GitURL}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "AGPL-3.0-or-later"
      "org.opencontainers.image.base.name": "scratch"
    annotations:
      "org.opencontainers.image.authors": "Georg Mangold"
      "org.opencontainers.image.vendor": "Georg Mangold"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.description": "A graphical user interface for MinIO®"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Tag}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
      "org.opencontainers.image.documentation": "{{.GitURL}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "AGPL-3.0-or-later"
      "org.opencontainers.image.base.name": "scratch"
